server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.100.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets: [localhost]
        labels:
          job: varlogs
          host: ec2-prometheus
          __path__: /var/log/*.log

  - job_name: docker-container
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: container
        regex: '/(.*)'
        replacement: '$1'

      - source_labels: ['__meta_docker_container_image']
        target_label: image

      - source_labels: ['__meta_docker_container_id']
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/*-json.log

      - target_label: job
        replacement: docker-container

      - target_label: host
        replacement: ec2-prometheus

    pipeline_stages:
      - docker: {}
