services:
  grafana:
    image: "grafana/grafana:latest" #11.3.0-security-01-ubuntu"
    container_name: "grafana"
    restart: "unless-stopped"
    ports:
      - "3000:3000"
    volumes:
      - "grafana:/var/lib/grafana"
      - "$PWD/grafana/grafana.ini:/etc/grafana/grafana.ini"
    depends_on:
      - cadvisor
    deploy:
     resources:
      limits:
       memory: 512M
      reservations:
       memory: 256M #minimum

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest #v0.49.1
    container_name: cadvisor
    privileged: true
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    devices:
      - /dev/kmsg
    depends_on:
      - redis
    deploy:
     resources:
      limits:
       memory: 256M
      reservations:
       memory: 128M

  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
    deploy:
     resources:
      limits:
       memory: 512M
      reservations:
       memory: 128M

#prometheus#
  prometheus:
    image: "prom/prometheus:latest" #v2.55.0"
    container_name: "prometheus"
    restart: "unless-stopped"
    privileged: true
    logging:
     driver: loki
     options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'
        loki-retries: 5
        loki-batch-size: 400
    ports:
      - "9090:9090"
    volumes:
      - "$PWD/prometheus:/etc/prometheus"
      - "prometheus:/prometheus"
    deploy:
     resources:
      limits:
       memory: 2G
      reservations:
       memory: 512M
#blackbox-exporter#
  blackbox_exporter:
     image: "quay.io/prometheus/blackbox-exporter:latest"
     container_name: "blackbox-exporter"
     restart: "unless-stopped"
     cap_add:
      - NET_RAW
     ports:
      - "9115:9115"
     volumes:
      - "./blackbox:/config"
     command:
      - "--config.file=/config/blackbox.yml"
     deploy:
      resources:
       limits:
        memory: 128M
       reservations:
        memory: 64M
#alertmanager#
  alertmanager:
    image: "prom/alertmanager:latest" #v0.27.0"
    container_name: "alertmanager"
    restart: "unless-stopped"
    ports:
      - "9093:9093"
    volumes:
      - "$PWD/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
      - "alertmanager:/alertmanager"
    deploy:
     resources:
      limits:
       memory: 256M
      reservations:
       memory: 128M
#Kuma#
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - './data:/app/data'
    deploy:
     resources:
      limits:
       memory: 512M
      reservations:
       memory: 256M
#Loki#
  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    restart: unless-stopped
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki:/etc/loki
      - loki:/tmp
    deploy:
     resources:
      limits:
       memory: 1G
      reservations:
       memory: 256M

  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - ./promtail:/etc/promtail
      - /var/log:/var/log
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro
    privileged: true
    user: root
    deploy:
     resources:
      limits:
       memory: 256M
      reservations:
       memory: 128M
#routingweb#
  incident-webhook:
    build: ./incident-webhook
    container_name: incident-webhook
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1443805759514083461/ihM2neSs6gYk97Ni6AhvVBtG8Mw7HkQs9QVob5q9h_fxNAyz2FJJa3RPpRh_ed-4ST70
    volumes:
      - ./var/log:/var/log
    deploy:
     resources:
      limits:
       memory: 256M
      reservations:
       memory: 128M

#snmp#
  snmp_exporter:
    image: prom/snmp-exporter
    container_name: snmp-exporter
    restart: unless-stopped
#    volumes:
 #     - ./snmp:/etc/snmp_exporter
      #- ./snmp/snmp.yml:/etc/snmp_exporter/snmp.yml
    deploy:
     resources:
      limits:
       memory: 256M
      reservations:
       memory: 128M

#speedtest#
  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter
    container_name: speedtest-exporter
    ports:
      - '9798:9798'
    restart: unless-stopped
    deploy:
     resources:
      limits:
       memory: 128M
      reservations:
       memory: 64M
volumes:
  grafana: {}
  prometheus: {}
  alertmanager: {}
  uptime-kuma-storage: {}
  loki: {}

