server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: debx240
          __path__: /var/log/*.log

  # Systemd journal logs
  - job_name: systemd-journal-log
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
        host: debx240
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'
      - source_labels: ['__journal_priority_keyword']
        target_label: 'level'

  # Docker container logs
  - job_name: docker-container
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-container
          host: debx240
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      # Docker logs are JSON
      - json:
          expressions:
            log: log
            stream: stream
            time: time

      # Use Docker timestamp
      - timestamp:
          source: time
          format: RFC3339Nano

      # Expose stdout / stderr
      - labels:
          stream:

      # Output only message
      - output:
          source: log
   #docker_sd_configs:
      #- host: unix:///var/run/docker.sock
        #refresh_interval: 5s
    #relabel_configs:
      #- source_labels: ['__meta_docker_container_name']
        #regex: '/(.*)'
        #target_label: 'container'
      #- source_labels: ['__meta_docker_container_log_stream']
        #target_label: 'logstream'
      #- source_labels: ['__meta_docker_container_id']
        #target_label: 'container_id'
